export const ROOM_KEY_PREFIX = 'room-key:'
export const AI_GAME_KEY = 'ai-game'
export const AI_FRAME_START_KEY = 'ai-frame-start'
export const AI_MOVES_KEY = 'ai-moves'
export const ROOM_MOVES_KEY = 'room-moves'
export const MELEE_KEY_PREFIX = 'melee-key:'
